import { memorizationTemplate } from "./memorization-template";

const names = [
  ["اللَّهُ", "Allah", "Varlığı zorunlu, bütün kemal sıfatlarını kendinde toplayan tek ilâh"],
  ["الرَّحْمَنُ", "er-Rahmân", "Sonsuz merhametiyle lütuf ve ihsanda bulunan"],
  ["الرَّحِيمُ", "er-Rahîm", "Rahmetiyle her şeyi kuşatan"],
  ["الْمَلِكُ", "el-Melik", "Bütün varlıkların gerçek sahibi ve hükümdarı"],
  ["الْقُدُّوسُ", "el-Kuddûs", "Her türlü eksiklikten münezzeh olan"],
  ["السَّلَامُ", "es-Selâm", "Esenlik veren ve noksanlıklardan uzak olan"],
  ["الْمُؤْمِنُ", "el-Mü’min", "Güven veren ve kendisine güvenilen"],
  ["الْمُهَيْمِنُ", "el-Müheymin", "Her şeyi gözetip yöneten"],
  ["الْعَزِيزُ", "el-Azîz", "Mutlak galip ve izzet sahibi"],
  ["الْجَبَّارُ", "el-Cebbâr", "Kudreti her şeye yeten"],
  ["الْمُتَكَبِّرُ", "el-Mütekebbir", "Büyüklükte eşsiz olan"],
  ["الْخَالِقُ", "el-Hâlik", "Her şeyi ölçüyle yaratan"],
  ["الْبَارِئُ", "el-Bâri’", "Örneksiz ve kusursuz yaratan"],
  ["الْمُصَوِّرُ", "el-Musavvir", "Varlıklara şekil veren"],
  ["الْغَفَّارُ", "el-Gaffâr", "Günahları çokça örten ve bağışlayan"],
  ["الْقَهَّارُ", "el-Kahhâr", "Her şeye hükmeden mutlak galip"],
  ["الْوَهَّابُ", "el-Vehhâb", "Karşılıksız nimetler veren"],
  ["الرَّزَّاقُ", "er-Rezzâk", "Bütün rızıkları veren"],
  ["الْفَتَّاحُ", "el-Fettâh", "Hayır kapılarını açan ve hükmeden"],
  ["اَلْعَلِيمُ", "el-Alîm", "Her şeyi hakkıyla bilen"],
  ["الْقَابِضُ", "el-Kâbız", "Hikmetiyle daraltan ve teslim alan"],
  ["الْبَاسِطُ", "el-Bâsıt", "Hikmetiyle genişleten"],
  ["الْخَافِضُ", "el-Hâfıd", "Dilediğini alçaltan"],
  ["الرَّافِعُ", "er-Râfi‘", "Dilediğini yükselten"],
  ["الْمُعِزُّ", "el-Muizz", "İzzet ve şeref veren"],
  ["المُذِلُّ", "el-Müzill", "Dilediğini zillete düşüren"],
  ["السَّمِيعُ", "es-Semî‘", "Her şeyi işiten"],
  ["الْبَصِيرُ", "el-Basîr", "Her şeyi gören"],
  ["الْحَكَمُ", "el-Hakem", "Nihai hükmü veren"],
  ["الْعَدْلُ", "el-Adl", "Mutlak adalet sahibi"],
  ["اللَّطِيفُ", "el-Latîf", "En ince şeyleri bilen ve lütfeden"],
  ["الْخَبِيرُ", "el-Habîr", "Her şeyden haberdar olan"],
  ["الْحَلِيمُ", "el-Halîm", "Cezada acele etmeyen"],
  ["الْعَظِيمُ", "el-Azîm", "Pek yüce ve azametli olan"],
  ["الْغَفُورُ", "el-Gafûr", "Çok bağışlayan"],
  ["الشَّكُورُ", "eş-Şekûr", "Az amele çok karşılık veren"],
  ["الْعَلِيُّ", "el-Aliyy", "Çok yüce olan"],
  ["الْكَبِيرُ", "el-Kebîr", "Büyüklükte eşsiz olan"],
  ["الْحَفِيظُ", "el-Hafîz", "Her şeyi koruyup gözeten"],
  ["المُقيِت", "el-Mukît", "Rızık veren ve koruyan"],
  ["الْحسِيبُ", "el-Hasîb", "Hesaba çeken ve kuluna yeten"],
  ["الْجَلِيلُ", "el-Celîl", "Azamet ve ululuk sahibi"],
  ["الْكَرِيمُ", "el-Kerîm", "İkramı ve cömertliği bol olan"],
  ["الرَّقِيبُ", "er-Rakîb", "Her şeyi gözeten"],
  ["الْمُجِيبُ", "el-Mücîb", "Dualara karşılık veren"],
  ["الْوَاسِعُ", "el-Vâsi‘", "İlmi ve rahmeti her şeyi kuşatan"],
  ["الْحَكِيمُ", "el-Hakîm", "Her işi hikmetli olan"],
  ["الْوَدُودُ", "el-Vedûd", "Seven ve sevilen"],
  ["الْمَجِيدُ", "el-Mecîd", "Şanı yüce, ikramı bol olan"],
  ["الْبَاعِثُ", "el-Bâis", "Ölüleri dirilten ve elçiler gönderen"],
  ["الشَّهِيدُ", "eş-Şehîd", "Her şeye şahit olan"],
  ["الْحَقُّ", "el-Hakk", "Varlığı ve ulûhiyeti gerçek olan"],
  ["الْوَكِيلُ", "el-Vekîl", "Kendisine güvenilip dayanılan"],
  ["الْقَوِيُّ", "el-Kavî", "Kudreti her şeye yeten"],
  ["الْمَتِينُ", "el-Metîn", "Kuvveti sarsılmaz olan"],
  ["الْوَلِيُّ", "el-Velî", "Müminlerin dostu ve yardımcısı"],
  ["الْحَمِيدُ", "el-Hamîd", "Her türlü övgüye layık olan"],
  ["الْمُحْصِي", "el-Muhsî", "Her şeyin sayısını bilen"],
  ["الْمُبْدِئُ", "el-Mübdi’", "İlk defa yoktan yaratan"],
  ["الْمُعِيدُ", "el-Muîd", "Yaratmayı tekrar eden"],
  ["الْمُحْيِي", "el-Muhyî", "Hayat veren ve dirilten"],
  ["اَلْمُمِيتُ", "el-Mümît", "Ölümü yaratan"],
  ["الْحَيُّ", "el-Hayy", "Ezelî ve ebedî diri olan"],
  ["الْقَيُّومُ", "el-Kayyûm", "Her şeyi ayakta tutup yöneten"],
  ["الْوَاجِدُ", "el-Vâcid", "Hiçbir şeye muhtaç olmayan"],
  ["الْمَاجِدُ", "el-Mâcid", "Şanı yüce ve keremi bol olan"],
  ["الْواحِدُ", "el-Vâhid", "Tek ve ortağı olmayan"],
  ["الصَّمَدُ", "es-Samed", "Herkesin muhtaç olduğu, kendisi muhtaç olmayan"],
  ["الْقَادِرُ", "el-Kâdir", "Her şeye gücü yeten"],
  ["الْمُقْتَدِرُ", "el-Muktedir", "Kudreti sınırsız olan"],
  ["الْمُقَدِّمُ", "el-Mukaddim", "Dilediğini öne alan"],
  ["الْمُؤَخِّرُ", "el-Muahhir", "Dilediğini geriye bırakan"],
  ["الأوَّلُ", "el-Evvel", "Başlangıcı olmayan"],
  ["الآخِرُ", "el-Âhir", "Sonu olmayan"],
  ["الظَّاهِرُ", "ez-Zâhir", "Varlığı delilleriyle açık olan"],
  ["الْبَاطِنُ", "el-Bâtın", "Mahiyeti gizli, gizlilikleri bilen"],
  ["الْوَالِي", "el-Vâlî", "Kâinatı yöneten"],
  ["الْمُتَعَالِي", "el-Müteâlî", "Her noksanlıktan yüce olan"],
  ["الْبَرُّ", "el-Berr", "İyiliği ve ihsanı bol olan"],
  ["التَّوَابُ", "et-Tevvâb", "Tövbeleri çokça kabul eden"],
  ["الْمُنْتَقِمُ", "el-Müntakım", "Adaletiyle karşılık veren"],
  ["العَفُوُّ", "el-Afüvv", "Günahları silip affeden"],
  ["الرَّؤُوفُ", "er-Raûf", "Şefkati pek çok olan"],
  ["مَالِكُ الْمُلْكِ", "Mâlikü’l-Mülk", "Mülkün gerçek sahibi"],
  ["ذُوالْجَلَالِ وَالإكْرَامِ", "Zü’l-Celâli ve’l-İkrâm", "Yücelik ve ikram sahibi"],
  ["الْمُقْسِطُ", "el-Muksit", "Adaletle hükmeden"],
  ["الْجَامِعُ", "el-Câmi‘", "Dilediklerini bir araya getiren"],
  ["الْغَنِيُّ", "el-Ganî", "Hiçbir şeye muhtaç olmayan"],
  ["الْمُغْنِي", "el-Muğnî", "Zenginlik ve yeterlilik veren"],
  ["اَلْمَانِعُ", "el-Mâni‘", "Hikmetiyle engelleyen"],
  ["الضَّارَّ", "ed-Dârr", "Hikmetiyle zarar veren şeyleri yaratan"],
  ["النَّافِعُ", "en-Nâfi‘", "Fayda ve hayır veren"],
  ["النُّورُ", "en-Nûr", "Aydınlatan ve kalplere nur veren"],
  ["الْهَادِي", "el-Hâdî", "Doğru yolu gösteren"],
  ["الْبَدِيعُ", "el-Bedî‘", "Örneksiz yaratan"],
  ["اَلْبَاقِي", "el-Bâkî", "Varlığı sonsuz olan"],
  ["الْوَارِثُ", "el-Vâris", "Her şeyin gerçek sahibi"],
  ["الرَّشِيدُ", "er-Reşîd", "Doğru yolu gösteren, her işi isabetli olan"],
  ["الصَّبُورُ", "es-Sabûr", "Cezalandırmada acele etmeyen"],
] as const;

export const asmaAlHusnaCatalog = [memorizationTemplate(
  "asma-al-husna-99",
  "Esmâü’l-Hüsnâ · 99 İsim",
  names.map(([arabic]) => arabic).join("\n"),
  names.map(([, name, meaning], index) => `${index + 1}. ${name} — ${meaning}`).join("\n"),
  "Allah’ın meşhur doksan dokuz güzel ismini sırasıyla ezberlemek için hazırlanmış tek bir ezber kaydıdır.",
  "Diyanet İşleri Yüksek Kurulu · Tirmizî, Deavât, 83; İbn Mâce, Duâ, 10",
)];
