import type { DevotionalTemplate } from "../discovery-types";

const sourceNote = "Kaynak: İslam ve İhsan — En Faziletli Zikirler.";

const esmaulHusna = `اللَّهُ، الرَّحْمَنُ، الرَّحِيمُ، الْمَلِكُ، الْقُدُّوسُ، السَّلَامُ، الْمُؤْمِنُ، الْمُهَيْمِنُ، الْعَزِيزُ، الْجَبَّارُ، الْمُتَكَبِّرُ
الْخَالِقُ، الْبَارِئُ، الْمُصَوِّرُ، الْغَفَّارُ، الْقَهَّارُ، الْوَهَّابُ، الرَّزَّاقُ، الْفَتَّاحُ، الْعَلِيمُ، الْقَابِضُ
الْبَاسِطُ، الْخَافِضُ، الرَّافِعُ، الْمُعِزُّ، الْمُذِلُّ، السَّمِيعُ، الْبَصِيرُ، الْحَكَمُ، الْعَدْلُ، اللَّطِيفُ
الْخَبِيرُ، الْحَلِيمُ، الْعَظِيمُ، الْغَفُورُ، الشَّكُورُ، الْعَلِيُّ، الْكَبِيرُ، الْحَفِيظُ، الْمُقِيتُ، الْحَسِيبُ
الْجَلِيلُ، الْكَرِيمُ، الرَّقِيبُ، الْمُجِيبُ، الْوَاسِعُ، الْحَكِيمُ، الْوَدُودُ، الْمَجِيدُ، الْبَاعِثُ، الشَّهِيدُ
الْحَقُّ، الْوَكِيلُ، الْقَوِيُّ، الْمَتِينُ، الْوَلِيُّ، الْحَمِيدُ، الْمُحْصِي، الْمُبْدِئُ، الْمُعِيدُ، الْمُحْيِي
الْمُمِيتُ، الْحَيُّ، الْقَيُّومُ، الْوَاجِدُ، الْمَاجِدُ، الْوَاحِدُ، الصَّمَدُ، الْقَادِرُ، الْمُقْتَدِرُ، الْمُقَدِّمُ
الْمُؤَخِّرُ، الْأَوَّلُ، الْآخِرُ، الظَّاهِرُ، الْبَاطِنُ، الْوَالِي، الْمُتَعَالِي، الْبَرُّ، التَّوَّابُ، الْمُنْتَقِمُ
الْعَفُوُّ، الرَّؤُوفُ، مَالِكُ الْمُلْكِ، ذُو الْجَلَالِ وَالْإِكْرَامِ، الْمُقْسِطُ، الْجَامِعُ، الْغَنِيُّ، الْمُغْنِي، الْمَانِعُ
الضَّارُّ، النَّافِعُ، النُّورُ، الْهَادِي، الْبَدِيعُ، الْبَاقِي، الْوَارِثُ، الرَّشِيدُ، الصَّبُورُ`;

export const dhikrCatalog: DevotionalTemplate[] = [
  {
    id: "recommended-subhanallahi-wa-bihamdihi",
    name: "Sübhânallâhi ve bihamdihi",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    translation: "Allah’ı hamdiyle tesbih ederim.",
    details: `Ebû Hüreyre’den aktarılan rivayette, bu zikri bir günde yüz defa söyleyen kişinin hataları deniz köpüğü kadar çok olsa bile bağışlanacağı müjdelenir (Buhârî, Deavât, 65). Sayfa bunu müminler için büyük bir müjde olarak açıklar.\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: 100,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["morning", "forgiveness", "gratitude"],
  },
  {
    id: "recommended-subhanallahi-azim",
    name: "Sübhânallâhi ve bihamdihi, sübhânallâhi’l-azîm",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    translation: "Allah’ı hamdiyle tesbih ederim; yüce Allah’ı tesbih ederim.",
    details: `Bu iki ifadenin dile hafif, Rahmân’a sevgili ve mizanda ağır olduğu aktarılır (Buhârî, Deavât, 65). Aynı bölümde Allah’ı zikreden kimse diriye, zikretmeyen ise ölüye benzetilir; zikrin insanın dışını güzel amellerle, içini de ilim ve idrak nuruyla süslediği anlatılır.\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "name",
    expandedArabicSize: 1,
    contexts: ["morning", "gratitude"],
  },
  {
    id: "recommended-la-hawla",
    name: "Lâ havle ve lâ kuvvete illâ billâh",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    translation: "Güç ve kuvvet ancak Allah’ın yardımıyladır.",
    details: `Çokça söylenmesi tavsiye edilir ve “cennet hazinelerinden bir hazine” olarak anılır (Buhârî, Deavât, 50). Sayfada bunun, günahlardan korunma ve ibadete güç bulmanın ancak Allah’ın yardımıyla mümkün olduğunu teslim etmek olduğu açıklanır. Ayrıca doksan dokuz derde deva olduğu, bunların en hafifinin hüzün ve keder olduğu rivayetine yer verilir (Hâkim, I, 727).\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["protection", "relief"],
  },
  {
    id: "recommended-la-ilaha-illallah",
    name: "Lâ ilâhe illallah",
    arabic: "لَا إِلٰهَ إِلَّا اللَّهُ",
    translation: "Allah’tan başka ilâh yoktur.",
    details: `Tevhid sözü olan bu zikrin ölüm anında ferahlık, kıyamette nur olacağı aktarılır. İmanı yenilemek için çokça söylenmesi tavsiye edilir (İbn Hanbel, II, 359; Hâkim, IV, 285/7657). İhlâsla söylendiğinde Allah’ın rahmetine vesile olacağına dair rivayet de aktarılır (Tirmizî, Deavât, 86). Son sözü bu olan mümin için cennet müjdesine yer verilir (Ebû Dâvûd, Cenâiz, 15-16).\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["relief"],
  },
  {
    id: "recommended-la-ilaha-expanded",
    name: "Allah’ın kelimeleri ve yarattıkları adedince tevhid",
    arabic: "لَا إِلٰهَ إِلَّا اللَّهُ عَدَدَ كَلِمَاتِ اللَّهِ، لَا إِلٰهَ إِلَّا اللَّهُ عَدَدَ خَلْقِ اللَّهِ، لَا إِلٰهَ إِلَّا اللَّهُ زِنَةَ عَرْشِ اللَّهِ، لَا إِلٰهَ إِلَّا اللَّهُ مِلْءَ سَمَاوَاتِ اللَّهِ، وَلَا إِلٰهَ إِلَّا اللَّهُ مِثْلَ ذٰلِكَ مَعَهُ، وَاللَّهُ أَكْبَرُ مِثْلَ ذٰلِكَ مَعَهُ، وَالْحَمْدُ لِلَّهِ مِثْلَ ذٰلِكَ مَعَهُ",
    translation: "Allah’ın kelimeleri, yarattıkları ve gökleri dolduracak kadar; Arş’ın ağırlığınca Allah’tan başka ilâh yoktur. Bunların misli kadar Allah en büyüktür ve hamd Allah’adır.",
    details: `Sayfada Muâz’a hitaben aktarılan rivayette, on bin defa tevhid söylemekten daha kolay bazı kapsamlı ifadelerin öğretildiği belirtilir. Allah’ın kelimeleri ve yarattıkları adedince, Arş’ın ağırlığınca ve gökler dolusunca tevhid; ardından bunların misli kadar tekbir ve hamd söylenmesi anlatılır (Ali el-Müttâkî, I, 442/1910). Rivayette bu zikrin sevabını yazmaya bir meleğin güç yetiremeyeceği ifade edilir.\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "name",
    expandedArabicSize: 0,
    contexts: ["gratitude"],
  },
  {
    id: "recommended-four-phrases",
    name: "Dört büyük zikir",
    arabic: "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلٰهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ",
    translation: "Allah eksik sıfatlardan uzaktır; hamd Allah’adır; Allah’tan başka ilâh yoktur ve Allah en büyüktür.",
    details: `Tesbih, hamd, tevhid ve tekbiri tek ifadede bir araya getirir. Sayfada, önceki peygamberlerin de bundan daha üstün bir tesbihle Allah’ı zikretmediğini bildiren rivayete yer verilir (Ali el-Müttâkî, no: 2015). Ayrıca Allah’ın zikrinin kalbi dirilttiği ve sabah ile ikindi sonrasında zikre zaman ayrılmasının tavsiye edildiği anlatılır.\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "name",
    expandedArabicSize: 1,
    contexts: ["morning", "gratitude"],
  },
  {
    id: "seed-subhanallah",
    name: "Sübhanallah",
    arabic: "سُبْحَانَ اللَّهِ",
    translation: "Allah noksanlıklardan uzaktır.",
    details: `Allah’ın bütün eksikliklerden uzak olduğunu ifade eder. Namazların ardından Elhamdülillah ve Allahu Ekber ile birlikte otuz üçer defa söylenmesi tavsiye edilir; üçü toplam doksan dokuz eder. Ardından tevhid tamamlama zikrinin okunacağı aktarılır (Müslim, Mesâcid, 146; Ebû Dâvûd, Vitir, 2).\n\n${sourceNote}`,
    source: "Müslim, Mesâcid, 146",
    targetCount: 33,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["afterPrayer", "gratitude"],
  },
  {
    id: "seed-alhamdulillah",
    name: "Elhamdülillah",
    arabic: "الْحَمْدُ لِلَّهِ",
    translation: "Hamd ve şükür Allah’adır.",
    details: `Şükrü ve hamdi Allah’a yönelten bu ifade, namazların ardından Sübhanallah ve Allahu Ekber ile birlikte otuz üçer defa tavsiye edilir. Sayfada Elhamdülillah ayrıca duaların en faziletlisi olarak anılır (Tirmizî, Duâ, 9/3383).\n\n${sourceNote}`,
    source: "Müslim, Mesâcid, 146",
    targetCount: 33,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["afterPrayer", "gratitude"],
  },
  {
    id: "seed-allahuakbar",
    name: "Allahu Ekber",
    arabic: "اللَّهُ أَكْبَرُ",
    translation: "Allah en büyüktür.",
    details: `Allah’ın her şeyden büyük, üstün ve yüce olduğunu ifade eder. Namazların ardından Sübhanallah ve Elhamdülillah ile birlikte otuz üçer defa söylenmesi tavsiye edilir; ardından tevhid tamamlama zikriyle yüz sayısına ulaşılır.\n\n${sourceNote}`,
    source: "Müslim, Mesâcid, 146",
    targetCount: 33,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["afterPrayer", "gratitude"],
  },
  {
    id: "recommended-after-prayer-tahlil",
    name: "Namaz sonrası tevhid tamamlama zikri",
    arabic: "لَا إِلٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    translation: "Allah’tan başka ilâh yoktur; O tektir, ortağı yoktur. Mülk O’nundur, hamd O’nadır ve O’nun her şeye gücü yeter.",
    details: `Her namazdan sonra otuz üçer defa Sübhanallah, Elhamdülillah ve Allahu Ekber söylenerek doksan dokuza ulaşılmasının ardından bu tevhid cümlesiyle yüzün tamamlanması tavsiye edilir. Rivayette bunu yapan kişinin günahları deniz köpüğü kadar olsa bile bağışlanacağı bildirilir (Müslim, Mesâcid, 146; Ebû Dâvûd, Vitir, 2).\n\n${sourceNote}`,
    source: "Müslim, Mesâcid, 146",
    targetCount: 1,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "name",
    expandedArabicSize: 0,
    contexts: ["afterPrayer", "forgiveness"],
  },
  {
    id: "recommended-esmaul-husna",
    name: "Esmâü’l-Hüsnâ",
    arabic: esmaulHusna,
    translation: "Allah’ın en güzel isimleri.",
    details: `Allah’ın doksan dokuz güzel ismini öğrenip benimseyen kimse için cennet müjdesi aktarılır. Kaynak sayfa her ismi tek tek vererek kısa anlamlarını açıklar; isimler Allah’ın rahmet, hükümranlık, kudret, ilim, bağışlama, adalet, koruma ve yaratma gibi sıfatlarını hatırlatır (Buhârî, Deavât, 68; Tirmizî, Deavât, 83; Hâkim, I, 62).\n\n${sourceNote}`,
    source: "Buhârî, Deavât, 68",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "name",
    expandedArabicSize: 0,
    contexts: ["gratitude", "relief"],
  },
  {
    id: "seed-hasbunallah",
    name: "Hasbünallâhü ve ni’me’l-vekîl",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    translation: "Allah bize yeter; O ne güzel vekildir.",
    details: `Korkan kimseler için güvenli bir sığınak olarak anlatılır (Suyûtî, el-Câmiu’s-Sağîr, no: 3715). Kuvvetli iman ve teslimiyetle tekrarına devam edilmesinin, mala ve cana gelmesinden endişe edilen musibet ve tehlikelere karşı korunmaya vesile olacağı belirtilir.\n\n${sourceNote}`,
    source: "Âl-i İmrân, 3/173",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "arabic",
    expandedArabicSize: 1,
    contexts: ["protection", "relief"],
  },
  {
    id: "recommended-distress-dhikr",
    name: "Şiddet ve musibet zikri",
    arabic: "لَا إِلَهَ إِلَّا اللَّهُ الْحَلِيمُ الْكَرِيمُ، لَا إِلَهَ إِلَّا اللَّهُ الْعَلِيُّ الْعَظِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ السَّبْعِ وَرَبُّ الْعَرْشِ الْكَرِيمِ",
    translation: "Halîm ve Kerîm Allah’tan başka ilâh yoktur. Yüce ve Azîm Allah’tan başka ilâh yoktur. Yedi göğün ve şerefli Arş’ın Rabbi Allah’tan başka ilâh yoktur.",
    details: `Halîm ve Kerîm olan, yüce ve azamet sahibi Allah’tan başka ilâh bulunmadığını; yedi göğün ve şerefli Arş’ın Rabbinin Allah olduğunu ifade eder. Sayfada bu zikre devam edilmesinin Allah’ın izniyle şiddet ve musibetlerin ferahlık ve sevince dönüşmesine vesile olacağı aktarılır.\n\n${sourceNote}`,
    source: "İslam ve İhsan — En Faziletli Zikirler",
    targetCount: null,
    targetUnit: "count",
    targetUnitLabel: null,
    listDisplay: "name",
    expandedArabicSize: 0,
    contexts: ["protection", "relief"],
  },
];
