import { memorizationTemplate } from "./memorization-template";

const hadiths = [
  ["İslâm güzel ahlâktır", "إِنَّمَا بُعِثْتُ لِأُتَمِّمَ صَالِحَ الْأَخْلَاقِ", "Ben güzel ahlâkı tamamlamak üzere gönderildim.", "Ahmed b. Hanbel, el-Müsned, 2/381"],
  ["Din samimiyettir", "الدِّينُ النَّصِيحَةُ", "Din samimiyettir.", "Müslim, Îmân, 95"],
  ["Merhamet", "مَنْ لَا يَرْحَمِ النَّاسَ لَا يَرْحَمْهُ اللَّهُ", "İnsanlara merhamet etmeyene Allah merhamet etmez.", "Müslim, Fedâil, 66; Tirmizî, Birr, 16"],
  ["Kolaylaştırın", "يَسِّرُوا وَلَا تُعَسِّرُوا وَبَشِّرُوا وَلَا تُنَفِّرُوا", "Kolaylaştırın, güçleştirmeyin; müjdeleyin, nefret ettirmeyin.", "Buhârî, İlim, 12; Müslim, Cihâd, 6"],
  ["Hayâ", "إِذَا لَمْ تَسْتَحِ فَاصْنَعْ مَا شِئْتَ", "Utanmıyorsan dilediğini yap.", "Buhârî, Enbiyâ, 54; Ebû Dâvûd, Edeb, 6"],
  ["Hayra vesile olmak", "الدَّالُّ عَلَى الْخَيْرِ كَفَاعِلِهِ", "Hayra vesile olan, onu yapan gibidir.", "Tirmizî, İlim, 14"],
  ["Aynı hataya düşmemek", "لَا يُلْدَغُ الْمُؤْمِنُ مِنْ جُحْرٍ وَاحِدٍ مَرَّتَيْنِ", "Mümin aynı delikten iki defa sokulmaz.", "Buhârî, Edeb, 83; Müslim, Zühd, 63"],
  ["Takvâ ve güzel ahlâk", "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ", "Nerede olursan Allah’a karşı sorumluluğunu koru; kötülüğün ardından onu silecek bir iyilik yap ve insanlara güzel ahlâkla davran.", "Tirmizî, Birr, 55"],
  ["İşi güzel yapmak", "إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ", "Allah, bir işi yaptığınızda onu sağlam ve güzel yapmanızı sever.", "Taberânî, el-Mu‘cemü’l-Evsat, 1/275"],
  ["İmanın şubeleri", "الْإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَةً وَالْحَيَاءُ شُعْبَةٌ مِنَ الْإِيمَانِ", "İman yetmiş küsur şubedir; hayâ da imandandır.", "Buhârî, Îmân, 3; Müslim, Îmân, 57-58"],
  ["Kötülüğe karşı durmak", "مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ", "Bir kötülük gören onu eliyle; gücü yetmezse diliyle, buna da gücü yetmezse kalbiyle değiştirsin.", "Müslim, Îmân, 78"],
  ["Ateşin dokunmayacağı gözler", "عَيْنَانِ لَا تَمَسُّهُمَا النَّارُ عَيْنٌ بَكَتْ مِنْ خَشْيَةِ اللَّهِ وَعَيْنٌ بَاتَتْ تَحْرُسُ فِي سَبِيلِ اللَّهِ", "Allah korkusuyla ağlayan ve Allah yolunda nöbet tutan göze ateş dokunmaz.", "Tirmizî, Fedâilü’l-Cihâd, 12"],
  ["Zarar vermemek", "لَا ضَرَرَ وَلَا ضِرَارَ", "Zarar vermek de zarara zararla karşılık vermek de yoktur.", "İbn Mâce, Ahkâm, 17; Muvatta’, Akdıye, 31"],
  ["Kardeşi için istemek", "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", "Kendisi için istediğini kardeşi için de istemeyen tam iman etmiş olmaz.", "Buhârî, Îmân, 7; Müslim, Îmân, 71"],
  ["Müslümanın kardeşliği", "الْمُسْلِمُ أَخُو الْمُسْلِمِ لَا يَظْلِمُهُ وَلَا يُسْلِمُهُ", "Müslüman Müslümanın kardeşidir; ona zulmetmez ve onu yalnız bırakmaz.", "Buhârî, Mezâlim, 3; Müslim, Birr, 58"],
  ["Sevgi ve iman", "لَا تَدْخُلُونَ الْجَنَّةَ حَتَّى تُؤْمِنُوا وَلَا تُؤْمِنُوا حَتَّى تَحَابُّوا", "İman etmedikçe cennete giremez, birbirinizi sevmedikçe iman etmiş olmazsınız.", "Müslim, Îmân, 93"],
  ["Güven veren Müslüman", "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ", "Müslüman, insanların dilinden ve elinden güvende olduğu kimsedir.", "Buhârî, Îmân, 4; Müslim, Îmân, 64-65"],
  ["Kardeş olun", "لَا تَبَاغَضُوا وَلَا تَحَاسَدُوا وَلَا تَدَابَرُوا وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا", "Birbirinize kin tutmayın, haset etmeyin, sırt çevirmeyin; kardeş olun.", "Buhârî, Edeb, 57-58; Müslim, Birr, 23"],
  ["Doğruluk", "إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ", "Doğruluk iyiliğe, iyilik de cennete götürür.", "Buhârî, Edeb, 69; Müslim, Birr, 103-104"],
  ["Sözünde durmak", "لَا تُمَارِ أَخَاكَ وَلَا تُمَازِحْهُ وَلَا تَعِدْهُ مَوْعِدًا فَتُخْلِفَهُ", "Kardeşinle çekişme, onu incitecek şaka yapma ve tutmayacağın söz verme.", "Tirmizî, Birr, 58"],
  ["Tebessüm", "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ", "Kardeşine tebessüm etmen senin için sadakadır.", "Tirmizî, Birr, 36"],
  ["Kalpler ve ameller", "إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ", "Allah görünüşlerinize ve mallarınıza değil, kalplerinize ve amellerinize bakar.", "Müslim, Birr, 33"],
  ["Anne babanın rızası", "رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ وَسَخَطُ الرَّبِّ فِي سَخَطِ الْوَالِدِ", "Rabbin rızası anne babanın rızasında, öfkesi de onların öfkesindedir.", "Tirmizî, Birr, 3"],
  ["Kabul edilen dualar", "ثَلَاثُ دَعَوَاتٍ مُسْتَجَابَاتٌ دَعْوَةُ الْمَظْلُومِ وَدَعْوَةُ الْمُسَافِرِ وَدَعْوَةُ الْوَالِدِ لِوَلَدِهِ", "Mazlumun, yolcunun ve anne babanın evladı için duası kabul edilir.", "İbn Mâce, Duâ, 11; Ebû Dâvûd, Vitr, 29"],
  ["Güzel terbiye", "مَا نَحَلَ وَالِدٌ وَلَدًا مِنْ نَحْلٍ أَفْضَلَ مِنْ أَدَبٍ حَسَنٍ", "Hiçbir anne baba çocuğuna güzel terbiyeden üstün bir armağan veremez.", "Tirmizî, Birr, 33"],
  ["Ailesine iyi davranmak", "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي", "Sizin en hayırlınız ailesine karşı en iyi davranandır.", "Tirmizî, Menâkıb, 63; İbn Mâce, Nikâh, 50"],
  ["Küçük ve büyüğün hakkı", "لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيُوَقِّرْ كَبِيرَنَا", "Küçüğümüze merhamet etmeyen ve büyüğümüze saygı göstermeyen bizden değildir.", "Tirmizî, Birr, 15; Ebû Dâvûd, Edeb, 58"],
  ["Yetimi gözetmek", "أَنَا وَكَافِلُ الْيَتِيمِ فِي الْجَنَّةِ هَكَذَا", "Yetimi gözeten kimseyle ben cennette yan yana olacağız.", "Buhârî, Edeb, 24; Müslim, Zühd, 42"],
  ["Helâk eden yedi şey", "اجْتَنِبُوا السَّبْعَ الْمُوبِقَاتِ", "İnsanı helâke sürükleyen yedi büyük günahtan sakının.", "Buhârî, Vesâyâ, 23; Müslim, Îmân, 144"],
  ["Ya hayır söyle ya sus", "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ", "Allah’a ve âhiret gününe iman eden ya hayır söylesin ya da sussun.", "Buhârî, Edeb, 31; Müslim, Îmân, 74"],
  ["Komşu hakkı", "مَا زَالَ جِبْرِيلُ يُوصِينِي بِالْجَارِ حَتَّى ظَنَنْتُ أَنَّهُ سَيُوَرِّثُهُ", "Cebrâil komşuyu öyle çok tavsiye etti ki onu mirasçı kılacak sandım.", "Buhârî, Edeb, 28; Müslim, Birr, 140-141"],
  ["Dul ve yoksulu gözetmek", "السَّاعِي عَلَى الْأَرْمَلَةِ وَالْمِسْكِينِ كَالْمُجَاهِدِ فِي سَبِيلِ اللَّهِ", "Dul ve yoksulu gözeten, Allah yolunda gayret eden kimse gibidir.", "Buhârî, Nafakât, 1; Müslim, Zühd, 41"],
  ["Tevbe", "كُلُّ بَنِي آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ", "Her insan hata eder; hata edenlerin en hayırlısı tevbe edenlerdir.", "Tirmizî, Kıyâme, 49; İbn Mâce, Zühd, 30"],
  ["Müminin hâli", "عَجَبًا لِأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ", "Müminin hâli hayret vericidir; her işi onun için hayırdır.", "Müslim, Zühd, 64"],
  ["Aldatmamak", "مَنْ غَشَّنَا فَلَيْسَ مِنَّا", "Bizi aldatan bizden değildir.", "Müslim, Îmân, 164"],
  ["Söz taşımamak", "لَا يَدْخُلُ الْجَنَّةَ نَمَّامٌ", "Söz taşıyan kimse cennete giremez.", "Müslim, Îmân, 168"],
  ["İşçinin ücreti", "أَعْطُوا الْأَجِيرَ أَجْرَهُ قَبْلَ أَنْ يَجِفَّ عَرَقُهُ", "İşçinin ücretini teri kurumadan verin.", "İbn Mâce, Rühûn, 4"],
  ["Dikilen her ağaç", "مَا مِنْ مُسْلِمٍ يَغْرِسُ غَرْسًا أَوْ يَزْرَعُ زَرْعًا فَيَأْكُلُ مِنْهُ طَيْرٌ أَوْ إِنْسَانٌ أَوْ بَهِيمَةٌ إِلَّا كَانَ لَهُ بِهِ صَدَقَةٌ", "Bir Müslümanın diktiğinden insan, hayvan veya kuş yerse bu onun için sadaka olur.", "Buhârî, Müzâraa, 1; Müslim, Müsâkât, 7-10"],
  ["Kalp", "أَلَا وَإِنَّ فِي الْجَسَدِ مُضْغَةً إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ أَلَا وَهِيَ الْقَلْبُ", "Bedende bir parça vardır; o iyi olursa bütün beden iyi olur, bozulursa bütün beden bozulur. O kalptir.", "Buhârî, Îmân, 39; Müslim, Müsâkât, 107"],
  ["Rabbinizin cennetine girin", "اتَّقُوا اللَّهَ رَبَّكُمْ وَصَلُّوا خَمْسَكُمْ وَصُومُوا شَهْرَكُمْ وَأَدُّوا زَكَاةَ أَمْوَالِكُمْ وَأَطِيعُوا ذَا أَمْرِكُمْ تَدْخُلُوا جَنَّةَ رَبِّكُمْ", "Rabbinize karşı sorumluluğunuzu koruyun; beş vakit namazı kılın, Ramazan’ı tutun, zekâtı verin ve meşru yöneticinize itaat edin ki Rabbinizin cennetine giresiniz.", "Tirmizî, Cum‘a, 80"],
] as const;

export const shortHadithCatalog = hadiths.map(([title, arabic, translation, source], index) => memorizationTemplate(
  `short-hadith-${index + 1}`,
  `${index + 1}. Hadis · ${title}`,
  arabic,
  translation,
  "Ezberlemeyi kolaylaştırmak için kısa ve öz metniyle sunulan hadis-i şerif.",
  source,
));
