import type { DevotionalTemplate } from "./discovery-types";

export const surahTemplates: { moduleId: "memorization"; item: DevotionalTemplate }[] = [
  {
    moduleId: "memorization",
    item: {
      id: "recommended-fatiha-suresi",
      name: "Fâtiha Sûresi",
      arabic: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
      translation: "Rahmân ve Rahîm olan Allah'ın adıyla. Hamd, âlemlerin Rabbi Allah'a mahsustur. O, Rahmân'dır, Rahîm'dir. Din gününün mâlikidir. Yalnız Sana ibadet eder ve yalnız Senden yardım dileriz. Bizi dosdoğru yola ilet; kendilerine nimet verdiğin kimselerin yoluna, gazaba uğrayanların ve sapıtanların yoluna değil.",
      details: "Kur'ân-ı Kerîm'in ilk sûresi olup 'Ümmü'l-Kitâb' (Kitabın Anası) ve 'Şâfiye' olarak da anılır; her namaz rekatında okunması vaciptir.",
      source: "Kur'ân-ı Kerîm, 1. Sûre (Mekke dönemi, 7 âyet)",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["general", "relief", "morning", "afterPrayer"],
      bagCategories: ["surahs"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-ihlas-suresi",
      name: "İhlâs Sûresi",
      arabic: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ۝ قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
      translation: "Rahmân ve Rahîm olan Allah'ın adıyla. De ki: O Allah tektir. Allah Samed'dir (her şey O'na muhtaçtır, O hiçbir şeye muhtaç değildir). O doğurmamış ve doğmamıştır. Hiçbir şey O'na denk ve benzer değildir.",
      details: "Tevhid inancını en özlü ve mükemmel şekilde ifade eden sûredir. Fazileti Kur'an'ın üçte birine denk tutulmuştur (Buhârî, Fedâilü'l-Kur'ân, 13; Müslim, Müsâfirîn, 259).",
      source: "Kur'ân-ı Kerîm, 112. Sûre (Mekke dönemi, 4 âyet)",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["morning", "protection", "relief"],
      bagCategories: ["surahs"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-felak-suresi",
      name: "Felak Sûresi",
      arabic: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ۝ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ",
      translation: "Rahmân ve Rahîm olan Allah'ın adıyla. De ki: Sabahın Rabbine sığınırım; yarattığı şeylerin şerrinden, karanlığı çöktüğü zaman gecenin şerrinden, düğümlere üfleyen büyücülerin şerrinden ve haset ettiği zaman hasetçinin şerrinden.",
      details: "Muavvizeteyn (sığındırıcı iki sûre) olarak anılır. Resûlullah (s.a.v.) sabah, akşam ve yatmadan önce korunmak için okurdu (Buhârî, Fedâilü'l-Kur'ân, 14; Ebû Dâvûd, Edeb, 98).",
      source: "Kur'ân-ı Kerîm, 113. Sûre (Mekke dönemi, 5 âyet)",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["protection", "morning", "relief"],
      bagCategories: ["surahs"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-nas-suresi",
      name: "Nâs Sûresi",
      arabic: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ۝ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
      translation: "Rahmân ve Rahîm olan Allah'ın adıyla. De ki: İnsanların Rabbine, insanların Hükümranına, insanların İlâhına sığınırım; sinsi vesvesecinin şerrinden, insanların kalplerine vesvese verenlerin; cinlerden ve insanlardan olanların şerrinden.",
      details: "İç ve dış vesveselerden, şeytani tuzaklardan ve zararlı varlıklardan Allah'a sığınma niyazıdır (Buhârî, Tıb, 39; Tirmizî, Deavât, 20).",
      source: "Kur'ân-ı Kerîm, 114. Sûre (Mekke dönemi, 6 âyet)",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["protection", "morning", "relief"],
      bagCategories: ["surahs"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-kevser-suresi",
      name: "Kevser Sûresi",
      arabic: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ۝ إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ ۝ فَصَلِّ لِرَبِّكَ وَانْحَرْ ۝ إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ",
      translation: "Rahmân ve Rahîm olan Allah'ın adıyla. Şüphesiz biz sana Kevser'i (pek çok hayrı, bereketi ve cennet havuzunu) verdik. Öyleyse Rabbin için namaz kıl ve kurban kes. Asıl soyu kesik olan, sana buğzeden (düşmanlık eden) kimsedir.",
      details: "Kur'ân-ı Kerîm'in en kısa sûresi olup Peygamber Efendimiz'e verilen yüce nimetleri ve ilahi teselliyi bildirir.",
      source: "Kur'ân-ı Kerîm, 108. Sûre (Mekke dönemi, 3 âyet)",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["gratitude", "general", "relief"],
      bagCategories: ["surahs"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-asr-suresi",
      name: "Asr Sûresi",
      arabic: "بِسْمِ اللَّهِ الرَّحْمٰنِ الرَّحِيمِ ۝ وَالْعَصْرِ ۝ إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ ۝ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ",
      translation: "Rahmân ve Rahîm olan Allah'ın adıyla. Asra (zamana) yemin olsun ki, insan gerçekten ziyan içindedir. Ancak iman edip sâlih amel işleyenler, birbirine hakkı tavsiye edenler ve birbirine sabrı tavsiye edenler müstesnadır.",
      details: "İmam Şâfiî bu sûre hakkında: 'İnsanlar sadece bu sûreyi düşünüp amel etselerdi, bu onlara yeterdi' buyurmuştur.",
      source: "Kur'ân-ı Kerîm, 103. Sûre (Mekke dönemi, 3 âyet)",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["general", "relief"],
      bagCategories: ["surahs"],
    },
  },
];

