import type { DevotionalTemplate } from "./discovery-types";

export const memorizationTemplates: { moduleId: "memorization"; item: DevotionalTemplate }[] = [
  {
    moduleId: "memorization",
    item: {
      id: "recommended-ayetul-kursi",
      name: "Âyetü'l-Kürsî",
      arabic: "اللَّهُ لَا إِلٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ وَلَا يَئُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ",
      translation: "Allah, O'ndan başka hiçbir ilâh olmayandır; Hayy'dır (daima diridir), Kayyûm'dur (bütün varlığı yönetip ayakta tutandır). O'nu ne bir uyuklama tutabilir ne de bir uyku. Göklerdeki ve yerdeki her şey O'nundur. O'nun izni olmaksızın katında kim şefaat edebilir? O, kullarının önlerinde ve arkalarında olan her şeyi bilir. Onlar ise O'nun dilediği kadarından başka ilminden hiçbir şey kavrayamazlar. O'nun kürsüsü gökleri ve yeri kuşatmıştır. Onları koruyup gözetmek O'na asla ağır gelmez. O, çok yücedir, çok büyüktür.",
      details: "Kur'ân-ı Kerîm'in en faziletli âyeti olarak kabul edilir. Farz namazlardan sonra okuyan kimse ile cennet arasında sadece ölüm olduğu bildirilmiştir (Nesâî, es-Sünenü'l-kübrâ, VI, 30).",
      source: "Kur'ân-ı Kerîm, Bakara Sûresi, 255; Nesâî, es-Sünenü'l-kübrâ, VI, 30",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "protection", "morning", "relief"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-amenerrasulu",
      name: "Âmene'r-Resûlü",
      arabic: "آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِهِ وَقَالُوا سَمِعْنَا وَأَطَعْنَا غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ ۝ لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِنْ قَبْلِنَا رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
      translation: "Peygamber, Rabbinden kendisine indirilene iman etti, müminler de. Her biri Allah'a, meleklerine, kitaplarına ve peygamberlerine inandı: 'Biz O'nun peygamberleri arasında hiçbir ayrım yapmayız' dediler ve eklediler: 'İşittik ve itaat ettik; bağışlamanı dileriz ey Rabbimiz, dönüş ancak Sana'dır.' Allah hiçbir kimseye gücünün yettiğinden fazlasını yüklemez. Kazandığı iyilik kendi lehine, işlediği kötülük de kendi aleyhinedir. 'Rabbimiz! Unutur veya yanılırsak bizi sorumlu tutma! Rabbimiz! Bize bizden öncekilere yüklediğin gibi ağır yük yükleme! Rabbimiz! Gücümüzün yetmeyeceği şeyleri bize taşıtma! Bizi affet, bizi bağışla, bize acı! Sen bizim Mevlâmızsın; inkârcı topluluğa karşı bize yardım et!'",
      details: "Peygamber Efendimiz (s.a.v.): 'Her kim geceleyin Bakara sûresinin son iki âyetini okursa, bu iki âyet ona kâfidir (onu her türlü fenalıktan korur)' buyurmuştur (Buhârî, Megâzî, 12; Müslim, Müsâfirîn, 255).",
      source: "Kur'ân-ı Kerîm, Bakara Sûresi, 285-286; Buhârî, Megâzî, 12",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["protection", "relief", "forgiveness"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-hasr-son-ayetler",
      name: "Haşr Sûresi Son Âyetleri (Hüvallâhüllezî)",
      arabic: "هُوَ اللَّهُ الَّذِي لَا إِلٰهَ إِلَّا هُوَ عَالِمُ الْغَيْبِ وَالشَّهَادَةِ هُوَ الرَّحْمٰنُ الرَّحِيمُ ۝ هُوَ اللَّهُ الَّذِي لَا إِلٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ ۝ هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ لَهُ الْأَسْمَاءُ الْحُسْنَىٰ يُسَبِّحُ لَهُ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ وَهُوَ الْعَزِيزُ الْحَكِيمُ",
      translation: "O, kendisinden başka hiçbir ilâh bulunmayan Allah'tır. Gaybı da görünen âlemi de bilendir. O, Rahmân'dır, Rahîm'dir. O, kendisinden başka hiçbir ilâh bulunmayan Allah'tır. Mülkün gerçek sahibi, mukaddes olan, selâmete erdiren, güven veren, görüp gözeten, mutlak güç sahibi, dilediğini zorla yaptıran ve büyüklükte eşi olmayandır. Allah, onların ortak koştuklarından münezzehtir. O, yaratan, yoktan var eden, şekil veren Allah'tır. En güzel isimler O'nundur. Göklerde ve yerde olanların hepsi O'nu tesbih eder. O, mutlak güç sahibidir, hüküm ve hikmet sahibidir.",
      details: "Sabah ve akşam namazlarının ardından okunması gelenekleşmiş, Esma-i Hüsna'yı cem eden çok faziletli âyet-i kerimelerdir (Tirmizî, Fedâilü'l-Kur'ân, 22).",
      source: "Kur'ân-ı Kerîm, Haşr Sûresi, 22-24; Tirmizî, Fedâilü'l-Kur'ân, 22",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["morning", "afterPrayer", "gratitude"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-subhaneke",
      name: "Sübhâneke Duası",
      arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلٰهَ غَيْرُكَ",
      translation: "Allah'ım! Sen her türlü eksiklikten münezzehsin ve hamd Sana mahsustur. Senin ismin mübarektir, şanın ve azametin yücedir ve Senden başka hiçbir ilâh yoktur.",
      details: "Namazlarda iftitah tekbirinin hemen ardından okunan istiftah (başlangıç) tesbihidir.",
      source: "Ebû Dâvûd, Salât, 120; Tirmizî, Salât, 179",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["beforePrayer", "general"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-ettehiyyatu",
      name: "Ettehiyyâtü (Teşehhüd)",
      arabic: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
      translation: "Bütün hürmetler, dualar, mâlî ve bedenî ibadetler Allah'a aittir. Ey Peygamber! Selâm, Allah'ın rahmeti ve bereketleri senin üzerine olsun. Selâm bizim ve Allah'ın sâlih kullarının üzerine olsun. Şehâdet ederim ki Allah'tan başka hiçbir ilâh yoktur ve yine şehâdet ederim ki Muhammed O'nun kulu ve elçisidir.",
      details: "İbn Mes'ûd (r.a.): 'Resûlullah (s.a.v.) elimi elleri arasına alarak Kur'an'dan bir sûre öğretir gibi bana teşehhüdü öğretti' demiştir (Buhârî, Ezân, 148; Müslim, Salât, 55).",
      source: "Buhârî, Ezân, 148; Müslim, Salât, 55",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "general"],
    },
  },
  {
    moduleId: "memorization",
    item: {
      id: "recommended-salli-barik",
      name: "Allâhümme Salli ve Bârik Duaları",
      arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ ۝ اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
      translation: "Allah'ım! İbrâhim'e ve İbrâhim'in âline rahmet ettiğin gibi Muhammed'e ve Muhammed'in âline de rahmet eyle. Şüphesiz Sen çok övülen ve pek yücesin. Allah'ım! İbrâhim'e ve İbrâhim'in âline bereket verdiğin gibi Muhammed'e ve Muhammed'in âline de bereket ihsan eyle. Şüphesiz Sen çok övülen ve pek yücesin.",
      details: "Sahabe-i kiramın 'Sana nasıl salavat getirelim?' sorusu üzerine bizzat Peygamberimiz (s.a.v.) tarafından öğretilmiştir (Buhârî, Deavât, 32; Müslim, Salât, 65).",
      source: "Buhârî, Deavât, 32; Müslim, Salât, 65",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "gratitude", "general"],
    },
  },
];
