import type { DevotionalTemplate } from "./discovery-types";

export const dhikrTemplates: { moduleId: "dhikr"; item: DevotionalTemplate }[] = [
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-la-ilaha-illallah",
      name: "Lâ ilâhe illallah",
      arabic: "لَا إِلٰهَ إِلَّا اللَّهُ",
      translation: "Allah’tan başka ilâh yoktur.",
      details: "Tevhid sözü olan bu zikrin imanı tazelediği ve fazileti hadislerde bildirilmiştir (İbn Hanbel, II, 359; Tirmizî, Deavât, 86).",
      source: "Tirmizî, Deavât, 86; İbn Hanbel, II, 359",
      targetCount: null,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["relief", "morning"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-subhanallah",
      name: "Sübhânallâh",
      arabic: "سُبْحَانَ اللَّهِ",
      translation: "Allah her türlü eksiklik ve noksanlıktan münezzehtir.",
      details: "Farz namazların ardından 33'er defa tesbih, tahmid ve tekbir getirilmesi sünnettir (Müslim, Mesâcid, 146).",
      source: "Müslim, Mesâcid, 146",
      targetCount: 33,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "gratitude", "morning"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-elhamdulillah",
      name: "Elhamdülillâh",
      arabic: "الْحَمْدُ لِلَّهِ",
      translation: "Bütün övgüler, şükürler ve hamd Allah'a mahsustur.",
      details: "Namaz sonu tesbihatının tahmid bölümü olup duanın ve şükrün başıdır (Müslim, Mesâcid, 146; Tirmizî, Deavât, 86).",
      source: "Müslim, Mesâcid, 146; Tirmizî, Deavât, 86",
      targetCount: 33,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "gratitude", "morning"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-allahu-ekber",
      name: "Allâhu Ekber",
      arabic: "اللَّهُ أَكْبَرُ",
      translation: "Allah en büyüktür, her şeyden yücedir.",
      details: "Namaz tesbihatının tekbir rüknü olup Allah'ın büyüklüğünü ve azametini ikrardır (Müslim, Mesâcid, 146).",
      source: "Müslim, Mesâcid, 146",
      targetCount: 33,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "gratitude", "morning"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-astaghfirullah",
      name: "Estağfirullâhe ve etûbü ileyh",
      arabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
      translation: "Allah’tan bağışlanma diler ve O’na tevbe ederim.",
      details: "Resûlullah (s.a.v.): 'Günde yüz defa Allah'a istiğfar ederim' buyurmuştur (Buhârî, Deavât, 3; Müslim, Zikir, 41).",
      source: "Buhârî, Deavât, 3; Müslim, Zikir, 41",
      targetCount: 100,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["forgiveness", "morning", "relief"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-subhanallahi-ve-bihamdihi",
      name: "Sübhânallâhi ve bi-hamdihî, Sübhânallâhi'l-azîm",
      arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
      translation: "Allah'ı hamd ile tesbih ederim, Yüce Allah'ı tenzih ederim.",
      details: "Dile hafif, mizanda ağır, Rahmân'a sevgili iki mübarek kelimedir (Buhârî, Deavât, 65; Müslim, Zikir, 31).",
      source: "Buhârî, Deavât, 65; Müslim, Zikir, 31",
      targetCount: 100,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["gratitude", "morning", "afterPrayer"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-la-havle",
      name: "Lâ havle ve lâ kuvvete illâ billâh",
      arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
      translation: "Güç ve kuvvet ancak Allah'a aittir.",
      details: "Cennet hazinelerinden bir hazine olduğu hadis-i şerifte bildirilmiştir (Buhârî, Megâzî, 38; Müslim, Zikir, 44).",
      source: "Buhârî, Megâzî, 38; Müslim, Zikir, 44",
      targetCount: 100,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["relief", "protection"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-hasbunallah",
      name: "Hasbünallâhu ve ni'mel vekîl",
      arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
      translation: "Allah bize yeter, O ne güzel vekildir.",
      details: "Zorluk ve darlık anında müminlerin sığındığı azametli zikir (Âl-i İmrân Sûresi, 173; Buhârî, Tefsîr, 3/4).",
      source: "Kur'ân-ı Kerîm, Âl-i İmrân, 173; Buhârî, Tefsîr, 3/4",
      targetCount: null,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["protection", "relief"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-kelime-i-tevhid-tam",
      name: "Lâ ilâhe illallâhu vahdehû lâ şerîke leh",
      arabic: "لَا إِلٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
      translation: "Allah'tan başka ilâh yoktur; O tektir, ortağı yoktur. Mülk O'nundur, hamd O'na mahsustur. O'nun gücü her şeye yeter.",
      details: "Sabah ve akşam okunduğunda büyük ecir ve manevi koruma sağladığı bildirilmiştir (Buhârî, Deavât, 54; Müslim, Zikir, 26).",
      source: "Buhârî, Deavât, 54; Müslim, Zikir, 26",
      targetCount: 10,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["morning", "protection", "relief"],
    },
  },
  {
    moduleId: "dhikr",
    item: {
      id: "recommended-salavat",
      name: "Allâhümme salli alâ seyyidinâ Muhammed",
      arabic: "اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ",
      translation: "Allah’ım! Efendimiz Muhammed’e salât ve selâm eyle.",
      details: "Kim bana bir salavat getirirse, Allah ona on rahmet eder (Müslim, Salât, 70).",
      source: "Müslim, Salât, 70",
      targetCount: 100,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "arabic",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "gratitude", "morning"],
    },
  },
];

