import type { DevotionalTemplate } from "./discovery-types";

export const prayerTemplates: { moduleId: "prayers"; item: DevotionalTemplate }[] = [
  {
    moduleId: "prayers",
    item: {
      id: "recommended-rabbena-atina",
      name: "Rabbenâ Âtinâ Duası",
      arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      translation: "Rabbimiz! Bize dünyada da iyilik ve güzellik ver, ahirette de iyilik ve güzellik ver ve bizi cehennem ateşinin azabından koru.",
      details: "Peygamber Efendimiz'in (s.a.v.) en çok okuduğu kapsamlı dünya ve ahiret duasıdır (Buhârî, Deavât, 55; Müslim, Zikir, 26).",
      source: "Kur'ân-ı Kerîm, Bakara Sûresi, 201; Buhârî, Deavât, 55",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "general", "relief"],
    },
  },
  {
    moduleId: "prayers",
    item: {
      id: "recommended-rabbena-gfirli",
      name: "Rabbenâğfirlî Duası",
      arabic: "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
      translation: "Rabbimiz! Hesabın görüleceği günde beni, anne babamı ve bütün müminleri bağışla.",
      details: "İbrâhim Aleyhisselâm'ın nesli, ebeveyni ve tüm inananlar için yaptığı ve namazların son oturuşunda okunan mübarek dua.",
      source: "Kur'ân-ı Kerîm, İbrâhîm Sûresi, 41",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["afterPrayer", "forgiveness", "general"],
    },
  },
  {
    moduleId: "prayers",
    item: {
      id: "recommended-seyyidul-istigfar",
      name: "Seyyidü'l-İstiğfâr (Tevbelerin Efendisi)",
      arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
      translation: "Allah'ım! Sen benim Rabbimsin, Senden başka ilâh yoktur. Beni Sen yarattın ve ben Senin kulunum. Gücüm yettiğince Sana verdiğim söz ve ahid üzereyim. Yaptıklarımın şerrinden Sana sığınırım. Üzerimdeki nimetini itiraf eder, günahımı da kabul ederim; beni bağışla, şüphesiz günahları ancak Sen bağışlarsın.",
      details: "Resûlullah (s.a.v.): 'İstiğfarın efendisi budur; kim inanarak sabah veya akşam söyler ve o gün vefat ederse cennet ehlindendir' buyurmuştur (Buhârî, Deavât, 2).",
      source: "Buhârî, Deavât, 2, 16; Tirmizî, Deavât, 15",
      targetCount: 1,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["forgiveness", "morning", "protection"],
    },
  },
  {
    moduleId: "prayers",
    item: {
      id: "recommended-yunus-as-duasi",
      name: "Hz. Yûnus'un Sıkıntı ve Kurtuluş Duası",
      arabic: "لَا إِلٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
      translation: "Senden başka hiçbir ilâh yoktur. Seni her türlü noksanlıktan tenzih ederim. Gerçekten ben haksızlık edenlerden oldum.",
      details: "Resûl-i Ekrem (s.a.v.): 'Zünnûn'un balığın karnında yaptığı bu duayla dua eden hiçbir Müslüman yoktur ki Allah onun duasını kabul etmesin' buyurmuştur (Tirmizî, Deavât, 81).",
      source: "Kur'ân-ı Kerîm, Enbiyâ Sûresi, 87; Tirmizî, Deavât, 81",
      targetCount: 40,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["relief", "forgiveness", "protection"],
    },
  },
  {
    moduleId: "prayers",
    item: {
      id: "recommended-kalp-istikamet-duasi",
      name: "Kalp İstikameti Duası",
      arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",
      translation: "Ey kalpleri evirip çeviren Allah'ım! Kalbimi dinin ve rızan üzere sabit kıl.",
      details: "Ümmü Seleme (r.a.) validemiz, Peygamberimiz'in (s.a.v.) en sık yaptığı dualardan birinin bu olduğunu rivayet etmiştir (Tirmizî, Deavât, 89; İbn Mâce, Dua, 2).",
      source: "Tirmizî, Deavât, 89; İbn Mâce, Dua, 2",
      targetCount: 7,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["general", "morning", "relief"],
    },
  },
  {
    moduleId: "prayers",
    item: {
      id: "recommended-sifa-duasi",
      name: "Şifa ve Afiyet Duası",
      arabic: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَاسَ، اشْفِ أَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
      translation: "Allah'ım! Ey insanların Rabbi! Sıkıntıyı gider, şifa ver; Sen şifa verensin. Senin şifandan başka şifa yoktur; öyle bir şifa ver ki hiçbir hastalık bırakmasın.",
      details: "Peygamber Efendimiz (s.a.v.) bir hastayı ziyaret ettiğinde veya dua istediğinde bu Nebevî niyaz ile dua ederdi (Buhârî, Tıb, 38; Müslim, Selâm, 46).",
      source: "Buhârî, Tıb, 38; Müslim, Selâm, 46",
      targetCount: 3,
      targetUnit: "count",
      targetUnitLabel: null,
      listDisplay: "name",
      expandedArabicSize: 1,
      contexts: ["relief", "protection", "general"],
    },
  },
];
